name: Test input data

on:
  push:
    paths:
    - github_repos.json
    # Verify as well when changing validation
    - .github/workflows/validate-input.yaml
  pull_request:
    paths:
    - github_repos.json
    # Verify as well when changing validation
    - .github/workflows/validate-input.yaml

jobs:
  jsonlint:
    name: Lint JSON
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install sponge cmd
      run: |
        sudo apt-get install moreutils
    - name: verify syntax
      run: |
        jq 'empty' github_repos.json
    - name: verify format
      run: |
        jq '.' github_repos.json | sponge github_repos.json
        if [[ `git status --porcelain` ]]; then
          echo "File not formatted correctly"
          echo "Format with \`jq '.' github_repos.json | sponge github_repos.json\`"
          echo "Changes:"
          git diff;
          exit 1;
        fi
    - name: verify company order
      run: |
        jq '.GitHubRepos|=map_values(.institutions|=sort_by(.shortname))' github_repos.json | sponge github_repos.json
        if [[ `git status --porcelain` ]]; then
          echo "File companies not sorted correctly"
          echo "Fix with \`jq '.GitHubRepos|=map_values(.institutions|=sort_by(.shortname))' github_repos.json | sponge github_repos.json\`"
          echo "Changes:"
          git diff;
          exit 1;
        fi
